apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "danswer-stack.fullname" . }}-indexing-model
  labels:
    {{- include "danswer-stack.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    {{- .Values.indexCapability.deployment.updateStrategy | toYaml | nindent 4 }}
  selector:
    matchLabels:
      {{- include "danswer-stack.selectorLabels" . | nindent 6 }}
      {{- if .Values.indexCapability.deploymentLabels }}
      {{- toYaml .Values.indexCapability.deploymentLabels | nindent 6 }}
      {{- end }}
  template:
    metadata:
      {{- with .Values.indexCapability.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "danswer-stack.labels" . | nindent 8 }}
        {{- with .Values.indexCapability.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: indexing-model-server
        image: "{{ .Values.indexCapability.deployment.image.repository }}:{{ .Values.indexCapability.deployment.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.indexCapability.deployment.image.pullPolicy }}
        command: [ "uvicorn", "model_server.main:app", "--host", "0.0.0.0", "--port", "9000", "--limit-concurrency", "10" ]
        {{- if .Values.indexCapability.deployment.resources }}
        resources:
            {{- toYaml .Values.indexCapability.deployment.resources | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 9000
        envFrom:
          - configMapRef:
              name: {{ .Values.config.envConfigMapName }}
        env:
          - name: INDEXING_ONLY
            value: "{{ default "True" .Values.indexCapability.indexingOnly }}"
          {{- include "danswer-stack.envSecrets" . | nindent 10}}
        volumeMounts:
        {{- range .Values.indexCapability.volumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
        {{- end }}
      volumes:
      {{- range .Values.indexCapability.volumes }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .persistentVolumeClaim.claimName }}
      {{- end }}
