apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: background
  template:
    metadata:
      labels:
        app: background
    spec:
      containers:
      - name: background
        image: danswer/danswer-backend:latest
        imagePullPolicy: IfNotPresent
        command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
        # There are some extra values since this is shared between services
        # There are no conflicts though, extra env variables are simply ignored
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: danswer-secrets
              key: redis_password
        envFrom:
        - configMapRef:
            name: env-configmap
